// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "bc7e198e8bdee95de8a323396907d9de0bfb1162767f0fd6ba347d97d3ce30c8")
